name: "Tinker"
description: "Start playing with your Particle device from Home Assistant."
version: "1.0.0"
slug: "tinker"
panel_icon: mdi:chip
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  PARTICLE_AUTH:
  PARTICLE_EVENT: spark/status
  HASS_PUBLIC_URL:
schema:
  PARTICLE_AUTH: str
  PARTICLE_EVENT: str?
  HASS_PUBLIC_URL: str
ingress: true
homeassistant_api: true
